### ISSUE TITLE
request: None, kind: RpcError(ForUser("AccountNotFound: pubkey=xxxxxxxxxxxxxxxxx"))

### ISSUE THREAD

**Issue by BarryTong98** [HardhatChad/ore#14]
```
ore --rpc https://api.mainnet-beta.solana.com --keypair ~/.config/solana/id.json rewards
thread 'main' panicked at /home/barry/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-cli-0.4.4/src/utils.rs:28:10:
Failed to get miner account: Error { request: None, kind: RpcError(ForUser("AccountNotFound: pubkey=xxxxxxxxxxxxxxxxx")) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

did someone struggle with this issue?
I am operating the command on google cloud virtual machine. I have been deleted and created difference machine several times and still encounter this issue.

**Comment by feitian124** [comment]
same here，sometimes，for one of the account, the pubkey is not my pubkey

**Comment by BarryTong98** [comment]
> same here，sometimes，for one of the account, the pubkey is not my pubkey

Did you fixed this problem?

**Comment by godofbeans** [comment]
I'm having the same identical issue where it expects this miner account pubkey to exist that is different from my miner account pubkey...

**Comment by godofbeans** [comment]
Why did you close this if you didn't post your solution??
