### ISSUE TITLE
Transaction failed: Error { request: None, kind: Custom("Sim failed") }

### ISSUE THREAD

**Issue by Jaxiii** [HardhatChad/ore#4]
thread 'main' panicked at /Users/USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-cli-0.4.0/src/mine.rs:89:26:
Transaction failed: Error { request: None, kind: Custom("Sim failed") }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This is a recurring error here. 
Maybe try catch this and put some attempts before closing the process, since simulations may vary on network conditions and can work right up in the next attempt.

But besides that, everything is running fine.
<img width="755" alt="Captura de Tela 2024-04-02 às 18 57 39" src="https://github.com/HardhatChad/ore/assets/17258221/7d4802ea-c873-409b-b947-448de1072149">

**Comment by KevinQuantJIN** [comment]
The same error here, waiting for fixed

**Comment by MarianoAkaMery** [comment]
> thread 'main' panicked at /Users/USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-cli-0.4.0/src/mine.rs:89:26: Transaction failed: Error { request: None, kind: Custom("Sim failed") } note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> This is a recurring error here. Maybe try catch this and put some attempts before closing the process, since simulations may vary on network conditions and can work right up in the next attempt.
> 
> But besides that, everything is running fine. <img alt="Captura de Tela 2024-04-02 às 18 57 39" width="755" src="https://private-user-images.githubusercontent.com/17258221/318979034-7d4802ea-c873-409b-b947-448de1072149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzY5MDgsIm5iZiI6MTcxMjEzNjYwOCwicGF0aCI6Ii8xNzI1ODIyMS8zMTg5NzkwMzQtN2Q0ODAyZWEtYzg3My00MDliLWI5NDctNDQ4ZGUxMDcyMTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5MzAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MmRlZDVhODkyZTQ3YjNkYzhjMzRjZTZmYmNmMTg4ODlkNTY3YjY2M2JkYzRhMTFjNTRmMTI3Nzc5YzI2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uelhLdhBIqhESKoqhwY9xZjbnsg7uJ0h5ETfq3uqgZE">

Manage to get it started after adding some SOL, i'm not sure if this is the correct log message btw.

Do you know if possible to use a custom RPC?

![image](https://github.com/HardhatChad/ore/assets/42919644/b184b174-7372-4db1-b970-a36101226b6d)

**Comment by KevinQuantJIN** [comment]
> > thread 'main' panicked at /Users/USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-cli-0.4.0/src/mine.rs:89:26: Transaction failed: Error { request: None, kind: Custom("Sim failed") } note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > This is a recurring error here. Maybe try catch this and put some attempts before closing the process, since simulations may vary on network conditions and can work right up in the next attempt.
> > But besides that, everything is running fine. <img alt="Captura de Tela 2024-04-02 às 18 57 39" width="755" src="https://private-user-images.githubusercontent.com/17258221/318979034-7d4802ea-c873-409b-b947-448de1072149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzY5MDgsIm5iZiI6MTcxMjEzNjYwOCwicGF0aCI6Ii8xNzI1ODIyMS8zMTg5NzkwMzQtN2Q0ODAyZWEtYzg3My00MDliLWI5NDctNDQ4ZGUxMDcyMTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5MzAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MmRlZDVhODkyZTQ3YjNkYzhjMzRjZTZmYmNmMTg4ODlkNTY3YjY2M2JkYzRhMTFjNTRmMTI3Nzc5YzI2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uelhLdhBIqhESKoqhwY9xZjbnsg7uJ0h5ETfq3uqgZE">
> 
> Manage to get it started after adding some SOL, i'm not sure if this is the correct log message btw.
> 
> Do you know if possible to use a custom RPC?
> 
> ![image](https://private-user-images.githubusercontent.com/42919644/319126406-b184b174-7372-4db1-b970-a36101226b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzk1OTYsIm5iZiI6MTcxMjEzOTI5NiwicGF0aCI6Ii80MjkxOTY0NC8zMTkxMjY0MDYtYjE4NGIxNzQtNzM3Mi00ZGIxLWI5NzAtYTM2MTAxMjI2YjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEwMTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMDIzNjc0ZmRkYjgwZWRjN2IxODQ4Zjg2MTZlMDhmZDhjZTRhYmVhNGUzZmVmY2YyOWU1MTY2YmQ1NTllOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uUqfLwZZBB2yIiA5tTtWqnxaLxoU4qmfz6Hp5BLFJT4)

Tried alchemy custom RPC but failed. I don't know what exactly the problem is. After searching, I thought this maybe coudl be the Solana itself problem.

**Comment by Jaxiii** [comment]
mitigated by latest update. the error was result of 0x3 error in the simulation.

https://x.com/HardhatChad/status/1777158638953488797
